openimis/openimis-fe-social_protection_js

.eslintrc.json
.github/workflows/CI_and_build.yml
.github/workflows/eslint_check.yml
package.json
rollup.config.js
src/actions.js
src/components/BenefitPlanBeneficiariesActiveTab.js
src/components/BenefitPlanBeneficiariesFilter.js
src/components/BenefitPlanBeneficiariesGraduatedTab.js
src/components/BenefitPlanBeneficiariesListTab.js
src/components/BenefitPlanBeneficiariesPotentialTab.js
src/components/BenefitPlanBeneficiariesSearcher.js
src/components/BenefitPlanBeneficiariesSuspendedTab.js
src/components/BenefitPlanFilter.js
src/components/BenefitPlanHeadPanel.js
src/components/BenefitPlanSearcher.js
src/components/BenefitPlanTabPanel.js
src/constants.js
src/index.js
src/menus/BenefitPlanMainMenu.js
src/pages/BenefitPlanPage.js
src/pages/BenefitPlansPage.js
src/pickers/BeneficiaryStatusPicker.js
src/reducer.js
src/util/action-type.js
src/util/json-validate.js
src/util/styles.js

TICKET: [CM-116](https://openimis.atlassian.net/browse/CM-116)
[CM-116]: https://openimis.atlassian.net/browse/CM-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CM-116: Added eslint

---

src/components/BenefitPlanBeneficiariesFilter.js
src/components/BenefitPlanFilter.js

Change:
- Fix resetting search critieria using "Reset" button in _social_protection_ module.

hotfix: fix resetting search params using reset button

---

src/actions.js
src/components/BenefitPlanBeneficiariesSearcher.js

https://openimis.atlassian.net/browse/CM-105
It needs: https://github.com/openimis/openimis-be-social_protection_py/pull/11
Most of the work was done in the scope of https://github.com/openimis/openimis-fe-social_protection_js/pull/8 since I was creating a new group beneficiary page.

CM-105: update group export

---

src/actions.js
src/components/BenefitPlanHeadPanel.js
src/constants.js
src/translations/en.json

**[BE PR](https://github.com/openimis/openimis-be-social_protection_py/pull/15) REQUIRED**
[CM-99](https://openimis.atlassian.net/browse/CM-99)
Changes:
- Add description field to the Benefit Plan form.
- Adjust current create/update benefit plan mutations.
[CM-99]: https://openimis.atlassian.net/browse/CM-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CM-99: add description field to the benefit plan form

---

src/components/BenefitPlanGroupBeneficiariesSearcher.js
src/pages/BenefitPlanPage.js
src/reducer.js

https://openimis.atlassian.net/browse/CM-121

CM-121: address QA points

---

src/actions.js
src/pages/BenefitPackagePage.js

[CM-111](https://openimis.atlassian.net/browse/CM-111)
Changes:
- ID/UUID fix which allows to fetch group details.
[CM-111]: https://openimis.atlassian.net/browse/CM-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CM-110: id/uuid fix

---

src/actions.js
src/pages/BenefitPackagePage.js

[CM-111](https://openimis.atlassian.net/browse/CM-111)
Changes:
- ID/UUID fix which allows to fetch beneficiary details.
[CM-111]: https://openimis.atlassian.net/browse/CM-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CM-111: fix with id/uuid

---

src/components/BenefitPlanBeneficiariesFilter.js
src/components/BenefitPlanBeneficiariesSearcher.js
src/components/BenefitPlanHeadPanel.js
src/components/BenefitPlanSearcher.js

[CM-26](https://openimis.atlassian.net/browse/CM-26)
Changes:
- Enabled selecting any date if “Date to” is not specified.
- Restored the sorting button to  “Max Beneficiaries” column.
- Resolved the issue of errors occurring when changing the status, as well as ensuring proper filtration. Additionally, when users switch tabs, the status is now correctly displayed.
[CM-26]: https://openimis.atlassian.net/browse/CM-26?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CM-26: minor issues reported by QA

---

src/actions.js
src/components/BenefitPlanTabPanel.js
src/dialogs/BenefitPlanBeneficiariesUploadDialog.js
src/pickers/WorkflowsPicker.js
src/reducer.js
src/translations/en.json

TICKET: https://openimis.atlassian.net/browse/CM-163
Presentation of feature:

CM-163: added workflow trigerring on frontend

---

src/components/BenefitPlanGroupBeneficiariesFilter.js

This PR makes code work on server.

hotfix-status-filter

---

src/components/BenefitPlanGroupBeneficiariesSearcher.js

HOTFIX: Prevent error and allow to filter when changing tab/status in benefit plan.

hotfix: status error fix

---

src/actions.js
src/components/BenefitPackageMembersSearcher.js
src/components/BenefitPlanBeneficiariesSearcher.js
src/components/BenefitPlanGroupBeneficiariesSearcher.js
src/reducer.js

https://openimis.atlassian.net/browse/CM-158
This PR fixes bug with downloading when switching tabs.
It needs this first: https://github.com/openimis/openimis-fe-individual_js/pull/23

CM-158: fix download and switching tabs

---

src/components/BenefitPlanTasksSearcher.js
src/translations/en.json

https://openimis.atlassian.net/browse/CM-144
This PR changes translations and makes rows active if status is ACCEPTED..

CM-144: change translations

---

README.md
src/actions.js
src/components/BenefitPackagePlanPanel.js
src/components/BenefitPlanHeadPanel.js
src/components/BenefitPlanSearcher.js
src/components/BenefitPlanSearcherForEntities.js
src/reducer.js
src/translations/en.json

Reverts openimis/openimis-fe-social_protection_js#43

Revert "CM-197: change holder to institution"

---

src/components/tasks/CalculationSocialProtectionTasks.js
src/index.js
src/translations/en.json

TICKET: https://openimis.atlassian.net/browse/CM-299

CM-299: added calculation tasks

---

src/pickers/BenefitPlanPicker.js

https://openimis.atlassian.net/browse/CM-335
It needs: https://github.com/openimis/openimis-be-social_protection_py/pull/38

CM-335: fetch alphabetically ordered benefit plans

---

.github/workflows/ci.yaml
sonar-project.properties
src/pickers/BenefitPlanPicker.js
src/translations/en.json

MERGING RELEASE branches
Release release/23.10

MERGING RELEASE branches

---

src/actions.js
src/index.js
src/reducer.js

https://openimis.atlassian.net/browse/CM-359
This PR will allow to fetch fields of schemas of benefit plans
It needs: https://github.com/openimis/openimis-be-social_protection_py/pull/46

CM-359: allow to fetch fields from schemas

---

src/components/BenefitPlanTabPanel.js
src/constants.js

CM-452: (FE): Add button by contribution point the UI for initiating deduplication in benefit plans

---

src/components/tasks/BeneficiaryTasks.js

https://openimis.atlassian.net/browse/CM-473
It needs: 
https://github.com/openimis/openimis-fe-tasks_management_js/pull/26
https://github.com/openimis/openimis-be-tasks_management_py/pull/34

CM-473: adjust to business_data logic

---

src/components/tasks/ValidateImportValidItems.js
src/translations/en.json

CM-420: Add how many items are invalid in %

---

src/components/CollapsableErrorList.js

Changed display of error messages

---

src/pickers/BenefitPlanPicker.js

fix for TICKET: https://openimis.atlassian.net/browse/CM-711

CM-711: fix BenefitPlan Programme picker

---

src/components/BenefitPlanEligibilityCriteriaPanel.js
src/components/CollapsableErrorList.js
src/components/tasks/BenefitPlanTasks.js
src/constants.js
src/pages/BenefitPlanPage.js
src/pickers/BenefitPlanPicker.js
src/reducer.js
src/translations/en.json
src/util/advanced-criteria-utils.js

https://openimis.atlassian.net/browse/CM-737
It needs: https://github.com/openimis/openimis-fe-individual_js/pull/53, https://github.com/openimis/openimis-be-social_protection_py/pull/60

CM-737: add eligibility criteria to benefit plan

---

src/actions.js
src/components/BenefitPlanTabPanel.js
src/constants.js
src/dialogs/BenefitPlanBeneficiariesUploadDialog.js
src/translations/en.json

https://openimis.atlassian.net/browse/CM-766
It needs: 
https://github.com/openimis/openimis-be-social_protection_py/pull/63
https://github.com/openimis/openimis-fe-contribution_plan_js/pull/74
https://github.com/openimis/openimis-fe-payroll_js/pull/40

CM-766: go to payroll creation from benefit plan

---

src/actions.js
src/pickers/WorkflowsPicker.js

https://openimis.atlassian.net/browse/CM-726

CM-726: added adjustments related to backend gql for workflow

---

src/actions.js
src/components/BenefitPlanChangelogTab.js
src/components/BenefitPlanHistoryFilter.js
src/components/BenefitPlanHistorySearcher.js
src/constants.js
src/dialogs/BenefitPlanSchemaModal.js
src/index.js
src/reducer.js
src/translations/en.json

TICKET: https://openimis.atlassian.net/browse/CM-767

CM-767: added changelog for Programme

---

src/components/BenefitPlanTaskTab.js
src/constants.js
src/index.js
src/translations/en.json

CM-767: added tasks tab for Programme

---

src/components/BenefitPlanHistorySearcher.js

TICKET: https://openimis.atlassian.net/browse/CM-767

CM-767: iso dates fixed

---

src/components/BenefitPlanHistorySearcher.js

https://openimis.atlassian.net/browse/CM-767

CM-767: iso dates fixed date updated

---

src/actions.js
src/components/BenefitPackageBenefitsTab.js
src/components/CollapsableErrorList.js

https://openimis.atlassian.net/browse/CM-779

CM-779: added improvements for summary of benefits

---

src/components/tasks/BeneficiaryUploadApprovalTask.js
src/dialogs/BenefitPlanBeneficiariesUploadHistoryDialog.js

https://openimis.atlassian.net/browse/CM-712

CM-712: changed parameters in fetching tasks to approve individualsFeature/cm 712

---

src/components/BenefitPlanEligibilityCriteriaPanel.js

https://openimis.atlassian.net/browse/CM-773

CM-773: fix displaying of filters

---

src/menus/BenefitPlanMainMenu.js

MERGING develop into release/24.04

MERGING develop into release/24.04

---

src/constants.js
src/index.js
src/pickers/BeneficiaryPicker.js

https://openimis.atlassian.net/browse/CM-833

CM-833: added picker for Beneficiary

---

src/actions.js

TICKET: https://openimis.atlassian.net/browse/CM-818

CM-818: make the possibility to create payroll fro group from program view

---

src/actions.js
src/components/BenefitPackageBenefitsTab.js

TICKET: https://openimis.atlassian.net/browse/CM-919

CM-919: added adjustments for benefit tab for group beneficiaries
